//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThetaNetCore.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApiStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThetaNetCore.Resources.ApiStrings", typeof(ApiStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to charged.
        /// </summary>
        public static string BatteryState_Charged {
            get {
                return ResourceManager.GetString("BatteryState_Charged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to charging.
        /// </summary>
        public static string BatteryState_Charging {
            get {
                return ResourceManager.GetString("BatteryState_Charging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disconnect.
        /// </summary>
        public static string BatteryState_Disconnect {
            get {
                return ResourceManager.GetString("BatteryState_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery charge failure.
        /// </summary>
        public static string CameraError_BatteryChargeFail {
            get {
                return ResourceManager.GetString("CameraError_BatteryChargeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High battery temperature.
        /// </summary>
        public static string CameraError_BatteryHighTemperature {
            get {
                return ResourceManager.GetString("CameraError_BatteryHighTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media format error.
        /// </summary>
        public static string CameraError_CantUseThisCard {
            get {
                return ResourceManager.GetString("CameraError_CantUseThisCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware problem.
        /// </summary>
        public static string CameraError_CaptureHwFailed {
            get {
                return ResourceManager.GetString("CameraError_CaptureHwFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not access SD memory card.
        /// </summary>
        public static string CameraError_CardAccessFail {
            get {
                return ResourceManager.GetString("CameraError_CardAccessFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD card in not set.
        /// </summary>
        public static string CameraError_CardDetectFail {
            get {
                return ResourceManager.GetString("CameraError_CardDetectFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs a compass calibration.
        /// </summary>
        public static string CameraError_CompassCalibration {
            get {
                return ResourceManager.GetString("CameraError_CompassCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File number exceeded the limit.
        /// </summary>
        public static string CameraError_FileNumberError {
            get {
                return ResourceManager.GetString("CameraError_FileNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD card memory format error.
        /// </summary>
        public static string CameraError_FormatCard {
            get {
                return ResourceManager.GetString("CameraError_FormatCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal memory format error.
        /// </summary>
        public static string CameraError_FormatInternalMem {
            get {
                return ResourceManager.GetString("CameraError_FormatInternalMem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High board temperature.
        /// </summary>
        public static string CameraError_HighTemperature {
            get {
                return ResourceManager.GetString("CameraError_HighTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not access internal memory.
        /// </summary>
        public static string CameraError_InternalMemAccessFail {
            get {
                return ResourceManager.GetString("CameraError_InternalMemAccessFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date time is not being set.
        /// </summary>
        public static string CameraError_NoDateSetting {
            get {
                return ResourceManager.GetString("CameraError_NoDateSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient memory.
        /// </summary>
        public static string CameraError_NoMemory {
            get {
                return ResourceManager.GetString("CameraError_NoMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string CameraError_None {
            get {
                return ResourceManager.GetString("CameraError_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error.
        /// </summary>
        public static string CameraError_UnexpectedError {
            get {
                return ResourceManager.GetString("CameraError_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNKNOWN.
        /// </summary>
        public static string CameraError_Unknown {
            get {
                return ResourceManager.GetString("CameraError_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while writing.
        /// </summary>
        public static string CameraError_WritingData {
            get {
                return ResourceManager.GetString("CameraError_WritingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bracket shooting.
        /// </summary>
        public static string CaptureStatus_BracketShooting {
            get {
                return ResourceManager.GetString("CaptureStatus_BracketShooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idle.
        /// </summary>
        public static string CaptureStatus_Idle {
            get {
                return ResourceManager.GetString("CaptureStatus_Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to self-timer countdown.
        /// </summary>
        public static string CaptureStatus_SelfTimer {
            get {
                return ResourceManager.GetString("CaptureStatus_SelfTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shooting.
        /// </summary>
        public static string CaptureStatus_Shooting {
            get {
                return ResourceManager.GetString("CaptureStatus_Shooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid value.
        /// </summary>
        public static string Invalid_Value {
            get {
                return ResourceManager.GetString("Invalid_Value", resourceCulture);
            }
        }
    }
}
