//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThetaNetCoreApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThetaNetCoreApp.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you download photos from your Theta, they are saved in the &quot;Download Folder&quot;. &quot;Phot View Folder&quot; is a folder to view images in your PC. These are different so that you can view sherical images in other folders..
        /// </summary>
        public static string Desc_FolderSettings {
            get {
                return ResourceManager.GetString("Desc_FolderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error.
        /// </summary>
        public static string Err_Connection_Title {
            get {
                return ResourceManager.GetString("Err_Connection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download folder is not specified..
        /// </summary>
        public static string Err_DownloadFolder {
            get {
                return ResourceManager.GetString("Err_DownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred while getting preview image.
        /// </summary>
        public static string Err_PreviewImage {
            get {
                return ResourceManager.GetString("Err_PreviewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error while communicating Theta. 
        ///Check the connection..
        /// </summary>
        public static string Err_ThetaUnhandledError {
            get {
                return ResourceManager.GetString("Err_ThetaUnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string Header_Connection {
            get {
                return ResourceManager.GetString("Header_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string Header_Photos {
            get {
                return ResourceManager.GetString("Header_Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Pict..
        /// </summary>
        public static string Header_TakePict {
            get {
                return ResourceManager.GetString("Header_TakePict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Item_PhotoAll {
            get {
                return ResourceManager.GetString("Item_PhotoAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded.
        /// </summary>
        public static string Item_PhotoDownloaded {
            get {
                return ResourceManager.GetString("Item_PhotoDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Downloaded.
        /// </summary>
        public static string Item_PhotoNotDownloaded {
            get {
                return ResourceManager.GetString("Item_PhotoNotDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string Menu_Title_Camera {
            get {
                return ResourceManager.GetString("Menu_Title_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Menu_Title_Home {
            get {
                return ResourceManager.GetString("Menu_Title_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC.
        /// </summary>
        public static string Menu_Title_PC {
            get {
                return ResourceManager.GetString("Menu_Title_PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Menu_Title_Settings {
            get {
                return ResourceManager.GetString("Menu_Title_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose files to delete first..
        /// </summary>
        public static string Msg_ChooseFileToDelete {
            get {
                return ResourceManager.GetString("Msg_ChooseFileToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete these  {0} files?.
        /// </summary>
        public static string Msg_ConfirmToDelete {
            get {
                return ResourceManager.GetString("Msg_ConfirmToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection OK.
        /// </summary>
        public static string Msg_ConnectionOK {
            get {
                return ResourceManager.GetString("Msg_ConnectionOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading files : {0} / {1}.
        /// </summary>
        public static string Msg_FileLoading {
            get {
                return ResourceManager.GetString("Msg_FileLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting photos by dates.
        /// </summary>
        public static string Msg_FileSorting {
            get {
                return ResourceManager.GetString("Msg_FileSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing ....
        /// </summary>
        public static string Msg_Processing {
            get {
                return ResourceManager.GetString("Msg_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taking a picture..
        /// </summary>
        public static string Msg_TakingAPicture {
            get {
                return ResourceManager.GetString("Msg_TakingAPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try connecting....
        /// </summary>
        public static string Msg_TryConnecting {
            get {
                return ResourceManager.GetString("Msg_TryConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Configurable after model V).
        /// </summary>
        public static string Note_Configurable_AfterV {
            get {
                return ResourceManager.GetString("Note_Configurable_AfterV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aperture.
        /// </summary>
        public static string Title_Aperture {
            get {
                return ResourceManager.GetString("Title_Aperture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Level.
        /// </summary>
        public static string Title_BatteryLevel {
            get {
                return ResourceManager.GetString("Title_BatteryLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Status.
        /// </summary>
        public static string Title_BatteryStatus {
            get {
                return ResourceManager.GetString("Title_BatteryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Error.
        /// </summary>
        public static string Title_CameraError {
            get {
                return ResourceManager.GetString("Title_CameraError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Settings.
        /// </summary>
        public static string Title_CameraSettings {
            get {
                return ResourceManager.GetString("Title_CameraSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Status.
        /// </summary>
        public static string Title_CaptureStatus {
            get {
                return ResourceManager.GetString("Title_CaptureStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Connection.
        /// </summary>
        public static string Title_CheckConnection {
            get {
                return ResourceManager.GetString("Title_CheckConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Title_Clear {
            get {
                return ResourceManager.GetString("Title_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Temperature.
        /// </summary>
        public static string Title_ColorTemperature {
            get {
                return ResourceManager.GetString("Title_ColorTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delte files.
        /// </summary>
        public static string Title_ConfirmDelete {
            get {
                return ResourceManager.GetString("Title_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Folder.
        /// </summary>
        public static string Title_DownloadFolder {
            get {
                return ResourceManager.GetString("Title_DownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aperture priority.
        /// </summary>
        public static string Title_ExposureAperture {
            get {
                return ResourceManager.GetString("Title_ExposureAperture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self-timer (sec).
        /// </summary>
        public static string Title_ExposureDelay {
            get {
                return ResourceManager.GetString("Title_ExposureDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO priority.
        /// </summary>
        public static string Title_ExposureISO {
            get {
                return ResourceManager.GetString("Title_ExposureISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string Title_ExposureManual {
            get {
                return ResourceManager.GetString("Title_ExposureManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string Title_ExposureNormal {
            get {
                return ResourceManager.GetString("Title_ExposureNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure Settings.
        /// </summary>
        public static string Title_ExposureProgram {
            get {
                return ResourceManager.GetString("Title_ExposureProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutter priority.
        /// </summary>
        public static string Title_ExposureShutter {
            get {
                return ResourceManager.GetString("Title_ExposureShutter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Version.
        /// </summary>
        public static string Title_Firmware {
            get {
                return ResourceManager.GetString("Title_Firmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Settings.
        /// </summary>
        public static string Title_FolderSettings {
            get {
                return ResourceManager.GetString("Title_FolderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support GPS.
        /// </summary>
        public static string Title_GPS {
            get {
                return ResourceManager.GetString("Title_GPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Gyro.
        /// </summary>
        public static string Title_Gyro {
            get {
                return ResourceManager.GetString("Title_Gyro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Title_ImageSettings {
            get {
                return ResourceManager.GetString("Title_ImageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Title_Info {
            get {
                return ResourceManager.GetString("Title_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO sensitivity.
        /// </summary>
        public static string Title_Iso_Sensitivity {
            get {
                return ResourceManager.GetString("Title_Iso_Sensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string Title_Manufacturer {
            get {
                return ResourceManager.GetString("Title_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Title_Model {
            get {
                return ResourceManager.GetString("Title_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power off delay (sec).
        /// </summary>
        public static string Title_OffDelay {
            get {
                return ResourceManager.GetString("Title_OffDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo View Folder.
        /// </summary>
        public static string Title_PhotoFolder {
            get {
                return ResourceManager.GetString("Title_PhotoFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Title_PhotoSettings {
            get {
                return ResourceManager.GetString("Title_PhotoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.
        /// </summary>
        public static string Title_Plugin {
            get {
                return ResourceManager.GetString("Title_Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can be started.
        /// </summary>
        public static string Title_PluginBoot {
            get {
                return ResourceManager.GetString("Title_PluginBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit status.
        /// </summary>
        public static string Title_PluginExitStatus {
            get {
                return ResourceManager.GetString("Title_PluginExitStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsForeground.
        /// </summary>
        public static string Title_PluginForeground {
            get {
                return ResourceManager.GetString("Title_PluginForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Title_PluginMessage {
            get {
                return ResourceManager.GetString("Title_PluginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Title_PluginName {
            get {
                return ResourceManager.GetString("Title_PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package name.
        /// </summary>
        public static string Title_PluginPackageName {
            get {
                return ResourceManager.GetString("Title_PluginPackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsRunning.
        /// </summary>
        public static string Title_PluginRunning {
            get {
                return ResourceManager.GetString("Title_PluginRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Title_PluginType {
            get {
                return ResourceManager.GetString("Title_PluginType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Title_PluginVersion {
            get {
                return ResourceManager.GetString("Title_PluginVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is web server.
        /// </summary>
        public static string Title_PluginWebServer {
            get {
                return ResourceManager.GetString("Title_PluginWebServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Title_Preview {
            get {
                return ResourceManager.GetString("Title_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Format.
        /// </summary>
        public static string Title_PreviewFormat {
            get {
                return ResourceManager.GetString("Title_PreviewFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordable Time (sec).
        /// </summary>
        public static string Title_RecordableTime {
            get {
                return ResourceManager.GetString("Title_RecordableTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded Time (sec).
        /// </summary>
        public static string Title_RecordedTime {
            get {
                return ResourceManager.GetString("Title_RecordedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        public static string Title_Remaining {
            get {
                return ResourceManager.GetString("Title_Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Title_RemainingPhoto {
            get {
                return ResourceManager.GetString("Title_RemainingPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video (sec).
        /// </summary>
        public static string Title_RemainingVideo {
            get {
                return ResourceManager.GetString("Title_RemainingVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space (MB).
        /// </summary>
        public static string Title_RemainningSpace {
            get {
                return ResourceManager.GetString("Title_RemainningSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        public static string Title_SerialNumber {
            get {
                return ResourceManager.GetString("Title_SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutter Spead.
        /// </summary>
        public static string Title_ShutterSpeed {
            get {
                return ResourceManager.GetString("Title_ShutterSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutter Volume.
        /// </summary>
        public static string Title_ShutterVolume {
            get {
                return ResourceManager.GetString("Title_ShutterVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep delay (sec).
        /// </summary>
        public static string Title_SleepDelay {
            get {
                return ResourceManager.GetString("Title_SleepDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theta Win App Photo Viewer.
        /// </summary>
        public static string Title_SpherePhotoView {
            get {
                return ResourceManager.GetString("Title_SpherePhotoView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Statuses.
        /// </summary>
        public static string Title_Status {
            get {
                return ResourceManager.GetString("Title_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uptime (sec).
        /// </summary>
        public static string Title_Uptime {
            get {
                return ResourceManager.GetString("Title_Uptime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Title_Video {
            get {
                return ResourceManager.GetString("Title_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string Title_WB_Auto {
            get {
                return ResourceManager.GetString("Title_WB_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluorescent Light 4 (light bulb color).
        /// </summary>
        public static string Title_WB_BulbFluorescent {
            get {
                return ResourceManager.GetString("Title_WB_BulbFluorescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudy.
        /// </summary>
        public static string Title_WB_Cloudy {
            get {
                return ResourceManager.GetString("Title_WB_Cloudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Temperature setting.
        /// </summary>
        public static string Title_WB_ColorTemperature {
            get {
                return ResourceManager.GetString("Title_WB_ColorTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdoor.
        /// </summary>
        public static string Title_WB_DayLight {
            get {
                return ResourceManager.GetString("Title_WB_DayLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluorescent Light 1 (daylight).
        /// </summary>
        public static string Title_WB_DayLightFluorescent {
            get {
                return ResourceManager.GetString("Title_WB_DayLightFluorescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluorescent Light 3 (white).
        /// </summary>
        public static string Title_WB_Fluorescent {
            get {
                return ResourceManager.GetString("Title_WB_Fluorescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incandescent Light 1.
        /// </summary>
        public static string Title_WB_Incandescent {
            get {
                return ResourceManager.GetString("Title_WB_Incandescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shade.
        /// </summary>
        public static string Title_WB_Shade {
            get {
                return ResourceManager.GetString("Title_WB_Shade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incandescent Light 2.
        /// </summary>
        public static string Title_WB_WarmWhite {
            get {
                return ResourceManager.GetString("Title_WB_WarmWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluorescent Light 2 (natural white).
        /// </summary>
        public static string Title_WB_WhiteFluorescent {
            get {
                return ResourceManager.GetString("Title_WB_WhiteFluorescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White Balance.
        /// </summary>
        public static string Title_WhiteBalance {
            get {
                return ResourceManager.GetString("Title_WhiteBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toggle preview.
        /// </summary>
        public static string ToolTip_Preview {
            get {
                return ResourceManager.GetString("ToolTip_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shoot button.
        /// </summary>
        public static string ToolTip_Shatter {
            get {
                return ResourceManager.GetString("ToolTip_Shatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zoom.
        /// </summary>
        public static string ToolTip_Zoom {
            get {
                return ResourceManager.GetString("ToolTip_Zoom", resourceCulture);
            }
        }
    }
}
