//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThetaWinApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThetaWinApp.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error.
        /// </summary>
        public static string Err_Connection_Title {
            get {
                return ResourceManager.GetString("Err_Connection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Home.
        /// </summary>
        public static string Header_CameraHome {
            get {
                return ResourceManager.GetString("Header_CameraHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string Header_Photos {
            get {
                return ResourceManager.GetString("Header_Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Pict..
        /// </summary>
        public static string Header_TakePict {
            get {
                return ResourceManager.GetString("Header_TakePict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string Menu_Title_Camera {
            get {
                return ResourceManager.GetString("Menu_Title_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Menu_Title_Home {
            get {
                return ResourceManager.GetString("Menu_Title_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC.
        /// </summary>
        public static string Menu_Title_PC {
            get {
                return ResourceManager.GetString("Menu_Title_PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Menu_Title_Settings {
            get {
                return ResourceManager.GetString("Menu_Title_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection OK.
        /// </summary>
        public static string Msg_ConnectionOK {
            get {
                return ResourceManager.GetString("Msg_ConnectionOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try connecting....
        /// </summary>
        public static string Msg_TryConnecting {
            get {
                return ResourceManager.GetString("Msg_TryConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Level.
        /// </summary>
        public static string Title_BatteryLevel {
            get {
                return ResourceManager.GetString("Title_BatteryLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Status.
        /// </summary>
        public static string Title_BatteryStatus {
            get {
                return ResourceManager.GetString("Title_BatteryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Error.
        /// </summary>
        public static string Title_CameraError {
            get {
                return ResourceManager.GetString("Title_CameraError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Status.
        /// </summary>
        public static string Title_CaptureStatus {
            get {
                return ResourceManager.GetString("Title_CaptureStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Connection.
        /// </summary>
        public static string Title_CheckConnection {
            get {
                return ResourceManager.GetString("Title_CheckConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Version.
        /// </summary>
        public static string Title_Firmware {
            get {
                return ResourceManager.GetString("Title_Firmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture Folder.
        /// </summary>
        public static string Title_Folder {
            get {
                return ResourceManager.GetString("Title_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support GPS.
        /// </summary>
        public static string Title_GPS {
            get {
                return ResourceManager.GetString("Title_GPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Gyro.
        /// </summary>
        public static string Title_Gyro {
            get {
                return ResourceManager.GetString("Title_Gyro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Title_Info {
            get {
                return ResourceManager.GetString("Title_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string Title_Manufacturer {
            get {
                return ResourceManager.GetString("Title_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Title_Model {
            get {
                return ResourceManager.GetString("Title_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordable Time (sec).
        /// </summary>
        public static string Title_RecordableTime {
            get {
                return ResourceManager.GetString("Title_RecordableTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded Time (sec).
        /// </summary>
        public static string Title_RecordedTime {
            get {
                return ResourceManager.GetString("Title_RecordedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        public static string Title_SerialNumber {
            get {
                return ResourceManager.GetString("Title_SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Statuses.
        /// </summary>
        public static string Title_Status {
            get {
                return ResourceManager.GetString("Title_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uptime (sec).
        /// </summary>
        public static string Title_Uptime {
            get {
                return ResourceManager.GetString("Title_Uptime", resourceCulture);
            }
        }
    }
}
